### ISSUE TITLE
Add support for JsDelivr

### ISSUE THREAD

**Issue by lucasdcrk** [afeld/emoji-css#24]
Please add support for JsDelivr.com, it's awesome!

**Comment by afeld** [comment]
Already using the GitHub Pages as the CDN, so don't see a lot of benefit here. Thanks for the suggestion!

**Comment by lucasdcrk** [comment]
JsDelivr as way more advanced than Github Pages as a CDN (In fact GitHub Pages is not meant to be 
 CDN).

- Reliability (JsDelivr ensure 100% uptime)
- Concatenation (Nearly every library is compatible with JsDelivr so you can have all your dependencies like bootstrap, jquery, ... in a single CSS / JS file)
- Speed (Because JsDelivr IS a CDN, speeds are years ahead of what you would have with GitHub Pages)

There are many more reasons why you should make your repo compatible with JsDelivr (see: https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/)

**Comment by MartinKolarik** [comment]
@afeld in case you change your mind, supporting this is as simple as making a [GitHub release](https://github.com/afeld/emoji-css/releases) when you have a new version.

Alternatively, @lucasdcrk you could still fork the repo and link to your fork instead (but obviously it would be better to have it working with the official repo).

**Comment by afeld** [comment]
> GitHub Pages is not meant to be CDN

Not exactly true:

> when someone visits a Pages site, rather than GitHub serving the content directly, the page is served by a global Content Delivery Network

https://blog.github.com/2014-01-07-faster-more-awesome-github-pages/

---

> JsDelivr as way more advanced than Github Pages as a CDN

Yep, not disagreeing, but I don't need those features for this project.

**Comment by lucasdcrk** [comment]
@MartinKolarik 
Working on a npm fork

**Comment by MartinKolarik** [comment]
@afeld technically it *is* served by a CDN but it definitely wasn't designed primarily for that purpose, for example, GitHub pages use a very short cache time. Also, your project might not need the advanced features but this is more about people using your project - for example they might want to load this together with other css libs from jsDelivr in one request.

**Comment by lucasdcrk** [comment]
Found an equivalent on JsDelivr: https://www.jsdelivr.com/package/npm/emoji-awesome
