### ISSUE TITLE
Flags to change

### ISSUE THREAD

**Issue by dhieyson** [afeld/emoji-css#27]
Spain ->  em-es  to em-flag-es
Germany -> em-ge to em-flag-de
Russia -> em-ru to em-flag-ru
France -> em-fr to em-flag-fr
South Korea -> em-kr to em-flag-kr
Japan -> em-jp to em-flag-jp

**Comment by afeld** [comment]
I'm just going off of the names in [emoji-data](https://github.com/iamcal/emoji-data). I don't particularly care to keep my own list of edge cases, so feel free to open an issue there.

In 2eb132b I added support for using the "alternative names", meaning that `em-flag-es` etc. will now work, even though they aren't shown on the Emoji CSS homepage. Hope that helps!
