### ISSUE TITLE
Flag class names

### ISSUE THREAD

**Issue by stereoshoots** [afeld/emoji-css#29]
Hello.
I came across with not very logical flags class names. Most of developers store in their data bases only country ISO codes, such as gb, be, es, etc.
Some of flag class names start with **em-** prefix, such as class **em-es**. And also some of flag class names start with **em-flag-** prefix, such as class **em-flag-be**. This leads to mandatory storage of flag classes, although it would be possible to do just with ISO codes.

**Comment by afeld** [comment]
See https://github.com/afeld/emoji-css/issues/27#issuecomment-399831863.
