### ISSUE TITLE
There isn't the Italian flag on the website

### ISSUE THREAD

**Issue by gabrielegrillo** [afeld/emoji-css#36]
I tried to search "em-flag-it" but there isn't the flag!

**Comment by afeld** [comment]
`em-flag-it` [works](https://jsfiddle.net/tr02uw8x/), but the default name is `em-it`. Feel free to bring up that inconsistency with [emoji-data](https://github.com/iamcal/emoji-data), which is the source.

Also, pull requests to make the search better are welcome!
