### ISSUE TITLE
Bug on some flags

### ISSUE THREAD

**Issue by lilian-gnt** [afeld/emoji-css#39]
Hello,
I use the flags on my website, and I noticed that some flags had turned into a letter.

Here is a screenshot to show you this: **https://puu.sh/ExC1G/99bac921a5.png**

It looks like the letter is applied on the flag first with each change of letter.
It would be great if you could fix the problem.
Thank you.

**Comment by jamesckchk** [comment]
Please check the followings
em-flag-za goes to Z
em-flag-hk goes to H
em-ge goes to D

Please kindly fix it. Thank you.

**Comment by afeld** [comment]
This seems to be an issue with emoji-data being out of sync with twemoji (https://github.com/iamcal/emoji-data/issues/138) and the `update.rb` script in this repository not handling that well. Have tried rewriting the script a few times with different approaches, and none were great. Need to think on it.
