### ISSUE TITLE
bower component

### ISSUE THREAD

**Issue by Rex90** [afeld/emoji-css#4]
Hi - any chance of making this into a bower component? I tried to do this myself but for some reason I can't make the SCSS file compile with sass

```
c:\Code\emoji-css>sass emoji.scss emoji.css
Error: Invalid CSS after "}": expected selector or at-rule, was "{% for emo in s..."
        on line 15 of emoji.scss
  Use --trace for backtrace.
```

**Comment by doomedramen** [comment]
I would suggest that @afeld create a /dist version of this containing emoji.css and the folder of images for relative path.
Then @afeld wouldnt even have to submit to bower if they dont want to, the end user can just `bower install afeld/emoji-css` and use it

**Comment by doomedramen** [comment]
I have created a fork that uses gulp to build a spritesheet, it can be installed via bower `bower install --save wookoouk/emoji-css`

https://github.com/wookoouk/emoji-css

**Comment by Rex90** [comment]
Thanks @wookoouk

**Comment by afeld** [comment]
Bower is now deprecated, so not going to bother. Thanks anyway!
