### ISSUE TITLE
Cannot display emoji, mixed content error, insecure stylesheet.

### ISSUE THREAD

**Issue by OisinMoran** [afeld/emoji-css#41]
First of all, this is a super neat project! Thanks for making and sharing it!

I'm having an issue displaying these on my site, which uses HTTPS and I don't think the issue was there before. I'm getting the following error:

```
Mixed Content: The page at 'https://example.com' was loaded over HTTPS,
but requested an insecure stylesheet 'http://emoji-css.afeld.me/emoji.css'.
This request has been blocked; the content must be served over HTTPS.
```

But the code _does_ specify HTTPS, so I'm not sure what is happening here or how to fix it. Is the site redirecting HTTPS requests to HTTP?
```
<link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
```

Any help would be greatly appreciated.

**Comment by afeld** [comment]
Go ahead and switch over from

```html
<link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
```

to

```html
<link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">
```

Not sure why the HTTPS redirect isn't working properly, but I'll get that figured out.

**Comment by afeld** [comment]
Ok, enabled enforcing of HTTPS at the GitHub Pages level and that seemed to take care of the redirect.
