### ISSUE TITLE
Hosting on his own website

### ISSUE THREAD

**Issue by Inkoming** [afeld/emoji-css#43]
Is there a way to host the whole project on my own hosting instead of using this project one?
What are the files I should upload? What's the CSS link I need to reach inside my HEAD?

Thanks a lot (great work by the way!).

**Comment by afeld** [comment]
Sure! If you are just looking to host the stylesheet, just save a copy of [the generated CSS file](https://emoji-css.afeld.me/emoji.css). Note that the emoji themselves will still be served from the Twitter CDN—using self-hosted versions of all of those would be a bit more of a project. If you want the full site, follow [the development instructions](https://github.com/afeld/emoji-css#development) and you can use the contents of `_site/`.
