### ISSUE TITLE
Request: Link to generate random emoji  

### ISSUE THREAD

**Issue by m0m4x** [afeld/emoji-css#44]
Firstly, congrats and thank you for your work!
It would be nice it could be possible to request a random emoji with a fixed class.

Example:
`<i class="em em-random" aria-role="presentation" aria-label="EMOJI"></i>`

Thank you anyway!
Have a nice day

**Comment by afeld** [comment]
Hmm, I don't think that's possible with CSS, but you could write a bit of JavaScript to [get a random value from an array](https://stackoverflow.com/questions/5915096/get-random-item-from-javascript-array) of emoji names and then construct the class name if you wanted to do so. Hope that helps!
