### ISSUE TITLE
Enhancement: Add a javascript library to retrieve the CSS classname by its unicode representation

### ISSUE THREAD

**Issue by giuseppetrematerra** [afeld/emoji-css#46]
The title is self explanatory.

**Comment by afeld** [comment]
Can you elaborate on the use case?

**Comment by giuseppetrematerra** [comment]
I have some unicode characters representing emoji stored in a database. I would like to be able to retrieve the CSS representation of that emoji by using some sort of javascript library

**Comment by afeld** [comment]
Gotcha. That's out of scope for this project, but should be doable using [emoji-data](https://github.com/iamcal/emoji-data). Good luck!

**Comment by giuseppetrematerra** [comment]
I have made it more easy gathering the JSON emoji data and retrieving only the columns I needed through a python script.
This is an example of what I retrieved from the base JSON file.
```json
[{"name": "em-hash", "unicode": ["0023", "FE0F", "20E3"], "category": "Symbols"}]
```
