### ISSUE TITLE
Service out of order - Connection time out

### ISSUE THREAD

**Issue by trevlix-booking** [afeld/emoji-css#47]
Hi, domain https://emoji-css.afeld.me/ and also styleshett https://emoji-css.afeld.me/emoji.css does not work. 
After about a minute of loading (when it also blocks the loading of the website into which the CSS is inserted in the <head>), an error occurs: ERR_CONNECTION_TIMED_OUT
Will this nice service still work or has it been canceled?

**Comment by phpandrew** [comment]
The domain expired and someone forgot to renew it

https://www.namecheap.com/domains/whois/result?domain=afeld.me
Registrar Registration Expiration Date: 2021-09-29T06:19:05.00Z

**Comment by trevlix-booking** [comment]
> The domain expired and someone forgot to renew it
> 
> https://www.namecheap.com/domains/whois/result?domain=afeld.me Registrar Registration Expiration Date: 2021-09-29T06:19:05.00Z

Thank you for info. It's a pitty. Already rewriting templates for https://github.com/IonicaBizau/emoji.css It can be easily stored locally, so such a problem cannot occur.

**Comment by afeld** [comment]
Whoops! Apparently that domain wasn't auto-renewing 😬 Might take up to a day for the DNS to propagate, but should be back up.
