### ISSUE TITLE
GitHub is not a CDN

### ISSUE THREAD

**Issue by simondoescode** [afeld/emoji-css#7]
GitHub is not a CDN please remove this reference from the [demo site](https://afeld.github.io/emoji-css/)

`<link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">`

**Comment by afeld** [comment]
I'd accept a pull request to convert to using https://rawgit.com/. Thanks.

**Comment by afeld** [comment]
Also, GitHub Pages _is_ behind a CDN.

https://github.com/blog/1715-faster-more-awesome-github-pages
