### ISSUE TITLE
iOS 10 style emoji?

### ISSUE THREAD

**Issue by ghost** [afeld/emoji-css#9]
👱🏼👴🏻🤘

**Comment by asherism** [comment]
What he said ☝🏼☝🏼☝🏼

**Comment by afeld** [comment]
Would happily accept a pull request 😉 

/cc #2

**Comment by ghost** [comment]
@afeld I can help you :) currently digging to find a folder with all the new emoji

**Comment by asherism** [comment]
@afeld i've managed to scrape emojipedia.org/apple/ and save the 72x72 .pngs, however they're named according to the apple spec. is that acceptable?

**Comment by ghost** [comment]
#10

**Comment by asherism** [comment]
@afeld pls respond

**Comment by ghost** [comment]
@afeld :'(

**Comment by spaghett1c0de** [comment]
@afeld I wanna see the new emojis :'(

**Comment by afeld** [comment]
Sorry for the slow response folks. See my note in https://github.com/afeld/emoji-css/pull/10#issuecomment-347023149.
